name: Configure & Installing XAMPP
on:
  workflow_dispatch:
    inputs:
      server:
        description: "Target server hostname or IP"
        required: true
      user:
        description: "SSH username"
        required: true
jobs:
  XAMPP-INSTALLATION-CONFIGURATION:
    runs-on: self-hosted   
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v3
       
     - name: Install XAMPP On RHEL9 
       uses: appleboy/ssh-action@master
       with:
          host: ${{ github.event.inputs.server }}
          username: ${{ github.event.inputs.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Downloading and installing XAMPP ... "
            wget https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/8.2.12/xampp-linux-x64-8.2.12-0-installer.run -O /tmp/xampp-installer.run
            chmod +x /tmp/xampp-installer.run
            sudo /tmp/xampp-installer.run -- mode unattended
            echo "${{ secrets.SUDO_PASSWORD }}"
            echo "XAMPP installed successfully."
            # Start XAMPP services
            sudo /opt/lampp/lampp start
            echo "${{ secrets.SUDO_PASSWORD }}"
            echo "✅ XAMPP services started."
