name: Hello World

on: 

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: |
          echo "Hello ${{ vars.NAME }}"
          echo "My Repository name is  ${{ github.repository }}"
      - name: print message 2
        run: |
          echo "Your Designation is ${{ vars.DESIG }}"
          echo "My Repository name is  ${{ github.workflow }}"
      - name: print message like step 3
        run: |
          echo "Your are going to join at ${{ vars.COMPANY }}"
          echo "My Secreate value is  ${{ secrets.MY_KEY }}"
