
name: Configure SSH

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Target server hostname or IP"
        required: true
      user:
        description: "SSH username"
        required: true

jobs:
  SSH CONFIGURATION:
    runs-on: self-hosted   # Use your Linux runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: appleboy/ssh-action@master   # Node.js runtime, no Docker required
        with:
          host: ${{ github.event.inputs.server }}
          username: ${{ github.event.inputs.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH Connection succesfully..."
            
         
