name: Transfer File to the server
on:
  workflow_dispatch:
    inputs:
      server:
        description: "Please enter Target Server IP address"
        required: true
      user:
        description: "Please enter username"
        required: true
      target_path:
        required: true
        default: /tmp/Manoj

jobs:
  Transfer_File_Server:
    runs-on: self-hosted   
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Checkout another repo (manoj_temprepo)
        uses: actions/checkout@v3
        with:
          repository: Manoj9923/manoj_temprepo
          path: other-repo

      - name: Transfer file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ github.event.inputs.server }}
          username: ${{ github.event.inputs.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "other-repo/git.docx"
          target: ${{ github.event.inputs.target_path }}
